POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "duong1",
    "email": "otaku1462@gmail.com",
    "password": "1234"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "duong1",
    "password": "hihi"
}


### 


POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjM3NmNmMjA3ZDkxYjY3NWEzZDBmZjEiLCJpYXQiOjE2NDc5MjI2OTd9.RPkjjUVtCR4ZwIHfXhXLwcJoiVduqgY0r98Bj5HNwIY

{
    "title": "tester",
    "description": "Show demo",
    "url": "instagram.org",
    "status": "LEARNING"
}


###

GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjM3NmNmMjA3ZDkxYjY3NWEzZDBmZjEiLCJpYXQiOjE2NDc5MjI2OTd9.RPkjjUVtCR4ZwIHfXhXLwcJoiVduqgY0r98Bj5HNwIY


###

PUT http://localhost:5000/api/posts/62394e6d667728f0b4cbb78c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjM3NmNmMjA3ZDkxYjY3NWEzZDBmZjEiLCJpYXQiOjE2NDc5MjI2OTd9.RPkjjUVtCR4ZwIHfXhXLwcJoiVduqgY0r98Bj5HNwIY

{
    "title": "123456",
    "description": "ohgsdfjhklfgsdjhlkfdgsljkgsdf",
    "url": "random.org",
    "status": "LEARNED"
}


###

DELETE  http://localhost:5000/api/posts/62394e6d667728f0b4cbb78c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjM3NmNmMjA3ZDkxYjY3NWEzZDBmZjEiLCJpYXQiOjE2NDc5MjI2OTd9.RPkjjUVtCR4ZwIHfXhXLwcJoiVduqgY0r98Bj5HNwIY


###

POST http://localhost:5000/api/auth/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjM3NmNmMjA3ZDkxYjY3NWEzZDBmZjEiLCJpYXQiOjE2NDc5MjI2OTd9.RPkjjUVtCR4ZwIHfXhXLwcJoiVduqgY0r98Bj5HNwIY
Content-Type: application/json

{
    "password": "hihi"
}